"""message

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 17:13:21.893938
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], name=op.f('fk_messages_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_trip_id_sent_at', 'messages', ['trip_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_trip_id_sent_at', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
