"""rating

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24 17:15:44.055194
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('rating_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('rater_id', sa.Uuid(), nullable=False),
    sa.Column('rated_user_id', sa.Uuid(), nullable=False),
    sa.Column('role_context', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.CheckConstraint("role_context IN ('driver_to_passenger', 'passenger_to_driver')", name=op.f('ck_ratings_role_context_valid')),
    sa.CheckConstraint('rater_id <> rated_user_id', name=op.f('ck_ratings_not_self')),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name=op.f('ck_ratings_score_range')),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.user_id'], name=op.f('fk_ratings_rated_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.user_id'], name=op.f('fk_ratings_rater_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], name=op.f('fk_ratings_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('trip_id', 'rater_id', 'rated_user_id', name='uq_ratings_trip_rater_rated')
    )
    op.create_index(op.f('ix_ratings_rated_user_id'), 'ratings', ['rated_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_rated_user_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
