"""trip

Revision ID: 20260924_0003_trip
Revises: 20260924_0002_vehicles
Create Date: 2026-09-24 17:04:02.791702
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20260924_0003_trip'
down_revision: str | None = '20260924_0002_vehicles'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Text(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('published', 'ongoing', 'completed', 'cancelled', name='trip_status'), server_default='published', nullable=False),
    sa.Column('estimated_total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_seat', sa.Float(), nullable=False),
    sa.CheckConstraint('available_seats >= 0', name=op.f('ck_trips_available_seats_non_negative')),
    sa.CheckConstraint('cost_per_seat >= 0', name=op.f('ck_trips_cost_per_seat_non_negative')),
    sa.CheckConstraint('destination_lat BETWEEN -90 AND 90', name=op.f('ck_trips_destination_lat_range')),
    sa.CheckConstraint('destination_lng BETWEEN -180 AND 180', name=op.f('ck_trips_destination_lng_range')),
    sa.CheckConstraint('origin_lat BETWEEN -90 AND 90', name=op.f('ck_trips_origin_lat_range')),
    sa.CheckConstraint('origin_lng BETWEEN -180 AND 180', name=op.f('ck_trips_origin_lng_range')),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], name=op.f('fk_trips_driver_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], name=op.f('fk_trips_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trip_id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_status_departure_time', 'trips', ['status', 'departure_time'], unique=False)
    op.create_table('trip_matches',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('matched_trip_id', sa.Uuid(), nullable=False),
    sa.Column('route_similarity', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['matched_trip_id'], ['trips.trip_id'], name=op.f('fk_trip_matches_matched_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], name=op.f('fk_trip_matches_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_trip_matches'))
    )
    op.create_index(op.f('ix_trip_matches_trip_id'), 'trip_matches', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_matches_trip_id'), table_name='trip_matches')
    op.drop_table('trip_matches')
    op.drop_index('ix_trips_status_departure_time', table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
    sa.Enum(name='trip_status').drop(op.get_bind(), checkfirst=True)
