"""riderequest tripmember

Revision ID: 20260924_0004_requests_members
Revises: 20260924_0003_trip
Create Date: 2026-09-24 17:09:42.763639
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20260924_0004_requests_members'
down_revision: str | None = '20260924_0003_trip'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Text(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('pickup', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name=op.f('ck_ride_requests_status_valid')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], name=op.f('fk_ride_requests_requester_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], name=op.f('fk_ride_requests_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_ride_requests'))
    )
    op.create_index(op.f('ix_ride_requests_requester_id'), 'ride_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_ride_requests_trip_id'), 'ride_requests', ['trip_id'], unique=False)
    op.create_index('uq_ride_requests_active_per_requester', 'ride_requests', ['trip_id', 'requester_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'accepted')"))
    op.create_table('trip_members',
    sa.Column('trip_member_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ride_request_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled')", name=op.f('ck_trip_members_status_valid')),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.request_id'], name=op.f('fk_trip_members_ride_request_id_ride_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], name=op.f('fk_trip_members_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_trip_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_member_id', name=op.f('pk_trip_members')),
    sa.UniqueConstraint('ride_request_id', name=op.f('uq_trip_members_ride_request_id')),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_trip_members_trip_id_user_id')
    )
    op.create_index(op.f('ix_trip_members_user_id'), 'trip_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_members_user_id'), table_name='trip_members')
    op.drop_table('trip_members')
    op.drop_index('uq_ride_requests_active_per_requester', table_name='ride_requests', postgresql_where=sa.text("status IN ('pending', 'accepted')"))
    op.drop_index(op.f('ix_ride_requests_trip_id'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_requester_id'), table_name='ride_requests')
    op.drop_table('ride_requests')
    # ### end Alembic commands ###
