name: Lelaku CI

on:
  push:
    branches:
      - main
      - initialize-github-actions
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          config: .markdownlint.json
          globs: '**/*.md'
